<?php
 
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\IngredientsController;
use App\Http\Controllers\RecipeController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\INgredientRecipeController;
use App\Http\Controllers\UserIngredientController;

Route::get('/users', [UsersController::class, 'index']);
Route::post('/users', [UsersController::class, 'store']);
Route::put('/users/{userId}', [UsersController::class, 'update']);
Route::delete('/users/{userId}', [UsersController::class, 'destroy']);
Route::get('/usersIngredients', [UserIngredientController::class, 'index']);
Route::post('/usersIngredients', [UserIngredientController::class, 'store']);
Route::put('/usersIngredients/{userId}/{ingredientId}', [UserIngredientController::class, 'update']);
Route::delete('/usersIngredients/{userId}/{ingredientId}', [UserIngredientController::class, 'destroy']);
Route::get('/recipes', [RecipeController::class, 'index']);        
Route::post('/recipes', [RecipeController::class, 'store']);   
Route::put('/recipes/{id}', [RecipeController::class, 'update']);
Route::delete('/recipes/delete/{recipeId}', [RecipeController::class, 'destroy']);
Route::get('/comments', [CommentController::class, 'index']);
Route::post('/comments', [CommentController::class, 'store']);
Route::put('/comments/{id}', [CommentController::class, 'update']);
Route::delete('/comments/{id}', [CommentController::class, 'destroy']);
Route::get('/ingredients', [IngredientsController::class, 'index']);
Route::post('/ingredients', [IngredientsController::class, 'store']);    
Route::put('/ingredients/{id}', [IngredientsController::class, 'update']); 
Route::delete('/ingredients/{id}', [IngredientsController::class, 'destroy']); 
Route::get('/ingredient-recipe', [IngredientRecipeController::class, 'index']);
Route::post('/ingredient-recipe', [IngredientRecipeController::class, 'store']);
Route::put('/ingredient-recipe/{ingredientId}/{recipeId}', [IngredientRecipeController::class, 'update']);
Route::delete('/ingredient-recipe/{ingredientId}/{recipeId}', [IngredientRecipeController::class, 'destroy']);
Route::get('/users/getbyEmail/{email}', [UsersController::class, 'getbyEmail']);
Route::get('/users/MoreThan_bodyweightKg/{value}', [UsersController::class, 'MoreThan_bodyweightKg']);
Route::get('/users/LessThan_bodyweightKg/{value}', [UsersController::class, 'LessThan_bodyweightKg']);
Route::get('/users/hasFilter_profilePictureUrl', [UsersController::class, 'hasFilter_profilePictureUrl']);
Route::get('/usersIngredients/getById/{userId}/{ingredientId}', [UserIngredientController::class, 'getById']);
Route::get('/recipes/getbyId/{recipeId}', [RecipeController::class, 'getbyId']);
Route::get('/comments/getById/{id}', [CommentController::class, 'getById']);
Route::get('/comments/getByRecipeId/{recipeId}', [CommentController::class, 'getByRecipeId']);
Route::get('/comments/user/{userId}', [CommentController::class, 'getByUserId']);
Route::get('/ingredients/getById/{id}', [IngredientsController::class, 'getById']);
Route::get('/ingredients/getByName/{name}', [IngredientsController::class, 'getByName']); 
Route::get('/ingredients/fruits', [IngredientsController::class, 'getFruits']);    
Route::get('/ingredients/non-fruits', [IngredientsController::class, 'getNonFruits']);  
Route::get('/ingredients/kcal/more-than/{value}', [IngredientsController::class, 'MoreThan_kcalPerGram']);
Route::get('/ingredients/kcal/less-than/{value}', [IngredientsController::class, 'LessThan_kcalPerGram']); 
Route::get('/ingredient-recipe/recipe/{recipeId}', [IngredientRecipeController::class, 'getByRecipe']); 
Route::get('/recipes/getRecipeWithIngredients/{recipeId}', [RecipeController::class, 'getRecipeWithIngredients']);
Route::get('/recipes/getAllRecipesWithIngredients', [RecipeController::class, 'getAllRecipesWithIngredients']);
Route::post('/login', [UsersController::class, 'login']);
Route::post('/register', [UsersController::class, 'register']);
Route::post('/check-email', [UsersController::class, 'checkEmail']);
Route::post('/forgot-password', [UsersController::class, 'forgotPassword']);
Route::post('/reset-password', [UsersController::class, 'resetPassword']);
Route::get('/users/{userId}/ingredients', [UserIngredientController::class, 'getUserIngredients']);
Route::get('/users/recipes/{userId}', [RecipeController::class, 'getRecipesByUserId']);
Route::put('/users/updateCalories/{userId}', [UsersController::class, 'updateCalories']);
Route::post('/recipes/make/{userId}/{recipeId}', [RecipeController::class, 'makeRecipe']);
Route::post('/uploadProfileImage', [UsersController::class, 'uploadProfileImage']);
Route::put('/users/updateProfile/{id}', [UsersController::class, 'updateProfile']);